version: "3.8"
networks:
  caddy_network:
    name: caddy_network
    external: true
services:
  app:
    container_name: maset
    image: maset:latest
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - caddy_network